export const DATABASE_CONNECTION = 'DATABASE_CONNECTION'

export const USER_MODEL = 'USER_MODEL'
export const ITEM_MODEL = 'ITEM_MODEL'
export const COLLECTION_MODEL = 'COLLECTION_MODEL'
export const CATEGORY_MODEL = 'CATEGORY_MODEL'